### ISSUE TITLE
syncrypt clone using vault name

### ISSUE THREAD

**Issue by jotech** [syncrypt/client#10]
I have given a name to a vault and tried to clone it from another machine but `syncrypt clone  vault_name` does not work (contrary to `syncrypt clone  vault_id`). Would be helpful to use the shorter vault name, wouldn't it?

**Comment by lordi** [comment]
Yea that's a good idea. However, the server has no idea of the vault name because it belongs to the encrypted metadata. So to implement this, the client would need to download all available vault metadata and compare the vault name. Definitely something we should do. The GUI client will also have to do this.
